### ISSUE TITLE
Boop Front

### ISSUE THREAD

**Issue by Cottean** [West3D-Printing/Micron#1]
Invalid link: 
The DragonBurner toolhead requires a modified Boop front: https://github.com/chirpy2605/voron/blob/main/general/Experimental/Boop/boop_front.stl

**Comment by Cottean** [comment]
Looks like it was moved to https://github.com/chirpy2605/voron/tree/main/general/Alternative_Voron_Mounts

**Comment by allenrowand** [comment]
Fixed, thank you
